name: whitemetals
favicon: null
layout_spectrum: 0.57996
typography_spectrum: 1
title: Creative. Content. Consulting.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71beb8'
    - '#15a79d'
    - '#ffffff'
    - '#43b0a8'
    - '#c1e2e0'
  brandStrength: 0
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
