name: whitemetals
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71beb8'
    - '#15a79d'
    - '#ffffff'
    - '#43b0a8'
    - '#c1e2e0'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
